export const AR_KEYS = {
  AUTH: "auth",
};

export const API_ROUTES = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/registro/cliente",
    REGISTER_COOPERATIVA: "/auth/registro/cooperativa",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  }, ER: {
    PROFILE: "/user/profile",
    UPDATE_PROFILE: "/user/profile",
    CHANGE_PASSWORD: "/user/change-password",
  },
  CLIENTES: {
    GET_ALL: "/clientes",
    CREATE: "/clientes",
    GET_BY_ID: "/clientes/:id",
    UPDATE: "/clientes/:id",
    DELETE: "/clientes/:id",
  },
  CONFIGURACION_DESCUENTOS: {
    GET_ALL: "/configuracion-descuentos",
    CREATE: "/configuracion-descuentos",
    GET_BY_ID: "/configuracion-descuentos/:id",
    UPDATE: "/configuracion-descuentos/:id",
    DELETE: "/configuracion-descuentos/:id",
    ACTIVAR: "/configuracion-descuentos/:id/activar",
    DESACTIVAR: "/configuracion-descuentos/:id/desactivar",
    GET_BY_TIPO: "/configuracion-descuentos/tipo/:tipo",
  },
  TENANTS: {
    GET_ALL: "/tenants",
    POST: "/tenants",
    GET_BY_ID: "/tenants/:id",
    UPDATE: "/tenants/:id",
    DELETE: "/tenants/:id",
  },
  CONFIG_TENANT: {
    GET_ALL: "/configuraciones-tenant",
    POST: "/configuraciones-tenant",
    GET_BY_ID: "/configuraciones-tenant/:id",
    UPDATE: "/configuraciones-tenant/:id",
    DELETE: "/configuraciones-tenant/:id",
  },
  RESOLUCIONES_ANT: {
    GET_ALL: "/resoluciones-ant",
    POST: "/resoluciones-ant",
    GET_BY_ID: "/resoluciones-ant/:id",
    UPDATE: "/resoluciones-ant/:id",
    DELETE: "/resoluciones-ant/:id",
  },
  RUTAS: {
    GET_ALL: "/rutas",
    CREATE: "/rutas",
    GET_BY_ID: "/rutas/:id",
    UPDATE: "/rutas/:id",
    DELETE: "/rutas/:id",
    GET_BY_TENANT: "/rutas/tenant/:tenantId",
  },
  TIPOS_RUTA_BUS: {
    GET_ALL: "/tipos-ruta-bus",
    CREATE: "/tipos-ruta-bus",
    GET_BY_ID: "/tipos-ruta-bus/:id",
    UPDATE: "/tipos-ruta-bus/:id",
    DELETE: "/tipos-ruta-bus/:id",
  },
  HORARIOS: {
    GET_ALL: "/horarios-ruta",
    CREATE: "/horarios-ruta",
    GET_BY_ID: "/horarios-ruta/:id",
    UPDATE: "/horarios-ruta/:id",
    DELETE: "/horarios-ruta/:id",
    GET_BY_RUTA: "/horarios-ruta?rutaId=:rutaId",
  },
  PARADAS: {
    GET_ALL: "/paradas-ruta",
    CREATE: "/paradas-ruta",
    GET_BY_ID: "/paradas-ruta/:id",
    UPDATE: "/paradas-ruta/:id",
    DELETE: "/paradas-ruta/:id",
    GET_BY_RUTA: "/paradas-ruta/ruta/:rutaId",
  },
  CIUDADES: {
    GET_ALL: "/ciudades",
    GET_BY_ID: "/ciudades/:id",
    GET_BY_NOMBRE: "/ciudades/nombre/:nombre",
    GET_BY_PROVINCIA: "/ciudades/provincia/:provincia",
  },
  USER_TENANT: {
    GET_ALL: "/usuario-tenant",
    POST: "/usuario-tenant",
    GET_BY_ID: "/usuario-tenant/:id",
    UPDATE: "/usuario-tenant/:id",
    DELETE: "/usuario-tenant/:id",
    POST_PERSONAL_INFO: "/usuario-tenant/:id/asignar-info-personal",
  },
  BUSES: {
    BASE: "/buses",
    MODELOS: "/modelos-bus",
    PISOS: "/pisos-bus",
    ASIENTOS: "/asientos",
    ASIENTOS_MASIVO: "/asientos/masivo"
  },
  DASHBOARD: {
    METRICAS_GENERALES: "/dashboard/metricas-generales",
    METRICAS_FINANCIERAS: "/dashboard/metricas-financieras",
    VIAJES_RECIENTES: "/dashboard/viajes-recientes",
    BOLETOS_RECIENTES: "/dashboard/boletos-recientes",
    OCUPACION_POR_TIPO_RUTA: "/dashboard/ocupacion-por-tipo-ruta",
    ESTADISTICAS_POR_DIA: "/dashboard/estadisticas-por-dia",
    RESUMEN_COMPLETO: "/dashboard/resumen-completo",
  }
};
